#
# Haiku buildmaster
#
# Runs buildmasters which connect to various builders
# at various remote locations over ssh with verifie
# host keys.
#
# TODO: buildmaster-packages-pvc is a strain on our
# infrastructure. We really need to get it to
# S3,Storj,etc "somehow". Given the difficulty of RWX
# mixed with the size of these volumes, all of these
# have to run on the same node reducing redundancy.
#
# We choose do-block-storage-retain as a storage class
# to "retain" PV's if this deployment is accidently
# deleted. In theory we could create a volume snapshot
# of the unattached volume and restore it to a new
# PVC via kubernetes.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: haikuporter
  labels:
    app: haikuporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: buildmaster
  template:
    metadata:
      labels:
        app: buildmaster
    spec:
      containers:
      - name: buildmaster-frontend
        image: ghcr.io/haikuports/haikuporter/frontend:1.2.8-5
        volumeMounts:
        - name: buildmaster-data-x86-gcc2
          mountPath: /var/instances/master/x86_gcc2
        - name: buildmaster-data-x86-64
          mountPath: /var/instances/master/x86_64
        - name: buildmaster-packages
          mountPath: /var/instances/haikuports
      - name: buildmaster-x86-64
        image: ghcr.io/haikuports/haikuporter/buildmaster:1.2.8-6
        #command: ["bootstrap", "x86_64"]
        command: ["loop"]
        volumeMounts:
        - name: buildmaster-packages
          mountPath: /var/packages
        - name: buildmaster-sources
          mountPath: /var/sources
        - name: buildmaster-data-x86-64
          mountPath: /var/buildmaster
        - name: signing-secrets
          mountPath: "/run/secrets/repo_signing"
          readOnly: true
        env:
          - name: SYSTEM_PACKAGE_BRANCH
            value: "r1beta5_111"
          - name: BUILD_TARGET_ARCH
            value: "x86_64"
          - name: REPOSITORY_TRIGGER_URL
            value: "https://depot.haiku-os.org/__repository/haikuports/source/haikuports_x86_64/import"
      - name: buildmaster-x86-gcc2
        image: ghcr.io/haikuports/haikuporter/buildmaster:1.2.8-6
        #command: ["bootstrap", "x86_gcc2", "x86"]
        command: ["loop"]
        volumeMounts:
        - name: buildmaster-sources
          mountPath: /var/sources
        - name: buildmaster-packages
          mountPath: /var/packages
        - name: buildmaster-data-x86-gcc2
          mountPath: /var/buildmaster
        - name: signing-secrets
          mountPath: "/run/secrets/repo_signing"
          readOnly: true
        env:
          - name: SYSTEM_PACKAGE_BRANCH
            value: "r1beta5_111"
          - name: BUILD_TARGET_ARCH
            value: "x86_gcc2"
          - name: REPOSITORY_TRIGGER_URL
            value: "https://depot.haiku-os.org/__repository/haikuports/source/haikuports_x86_gcc2/import"
      volumes:
        - name: buildmaster-data-x86-64
          persistentVolumeClaim:
            claimName: buildmaster-data-x86-64-pvc
        - name: buildmaster-data-x86-gcc2
          persistentVolumeClaim:
            claimName: buildmaster-data-x86-gcc2-pvc
        - name: buildmaster-packages
          persistentVolumeClaim:
            claimName: buildmaster-packages-pvc
        - name: buildmaster-sources
          persistentVolumeClaim:
            claimName: buildmaster-sources-pvc
        - name: signing-secrets
          projected:
            sources:
            - secret:
                name: haiku-artifact-signing
                items:
                  - key: minisign-haiku-2019.key
                    path: privatekey
                  - key: minisign-haiku-2019.password
                    path: privatekeypass
---
# state data for builds like logs of buildruns, buildrun id
# tracking, builder connection information.
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: buildmaster-data-x86-64-pvc
spec:
  storageClassName: do-block-storage-retain
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
# state data for builds like logs of buildruns, buildrun id
# tracking, builder connection information.
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: buildmaster-data-x86-gcc2-pvc
spec:
  storageClassName: do-block-storage-retain
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
# all of the packages for Haikuports
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: buildmaster-packages-pvc
spec:
  storageClassName: do-block-storage-retain
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 250Gi
---
# pretty much just Haiku sources at this point
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: buildmaster-sources-pvc
spec:
  storageClassName: do-block-storage-retain
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: Service
metadata:
  name: buildmaster
spec:
  selector:
    app: buildmaster
  ports:
  - name: www
    port: 80
    targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: www-build
  labels:
    app: www-build
spec:
  replicas: 1
  selector:
    matchLabels:
      app: www-build
  template:
    metadata:
      labels:
        app: www-build
    spec:
      containers:
      - name: www-build
        image: ghcr.io/haiku/www-build:latest
---
apiVersion: v1
kind: Service
metadata:
  name: www-build
spec:
  selector:
    app: www-build
  ports:
  - name: www
    port: 80
    targetPort: 80
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: strip-bm-prefix
spec:
  stripPrefix:
    prefixes:
      - /buildmaster/
      - /irccat/
---
# web frontend for buildmaster
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: buildmaster
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
    traefik.ingress.kubernetes.io/router.entrypoints: web,webs
    traefik.ingress.kubernetes.io/router.middlewares: default-strip-bm-prefix@kubernetescrd
spec:
  tls:
  - hosts:
    - build.haiku-os.org
    secretName: tls-cert-build
  rules:
  - host: build.haiku-os.org
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: www-build
            port:
              name: www
      - path: /buildmaster
        pathType: Prefix
        backend:
          service:
            name: buildmaster
            port:
              name: www
      - path: /irccat
        pathType: Prefix
        backend:
          service:
            name: irccat
            port:
              number: 80
