#
# Haiku buildmaster
#
# Runs buildmasters which connect to various builders
# at various remote locations over ssh with verifie
# host keys.
#
apiVersion: apps/v1
kind: Deployment
metadata:
  name: buildmaster-main
  labels:
    app: buildmaster
spec:
  replicas: 1
  selector:
    matchLabels:
      app: buildmaster
  template:
    metadata:
      labels:
        app: buildmaster
    spec:
      containers:
      - name: buildmaster-frontend
        image: ghcr.io/haikuports/haikuporter/frontend:1.3.1-28-gd668
        volumeMounts:
        - name: buildmaster-data-x86-64
          mountPath: /var/instances/master/x86_64
        - name: buildmaster-data-x86-gcc2
          mountPath: /var/instances/master/x86_gcc2
        - name: buildmaster-data-riscv64
          mountPath: /var/instances/master/riscv64
      - name: buildmaster-x86-64
        image: ghcr.io/haikuports/haikuporter/buildmaster:1.3.1-32-g6720
        #command: ["bootstrap", "x86_64"]
        command: ["loop"]
        volumeMounts:
        - name: buildmaster-sources
          mountPath: /var/sources
        - name: buildmaster-data-x86-64
          mountPath: /var/buildmaster
        - name: storage-secrets-master
          mountPath: "/run/secrets/storage_config"
        - name: signing-secrets
          mountPath: "/run/secrets/repo_signing"
          readOnly: true
        env:
          - name: STORAGE_BACKEND_CONFIG
            value: "/run/secrets/storage_config/storage-config-x86-64.json"
          - name: SYSTEM_PACKAGE_BRANCH
            value: "r1beta5_111"
          - name: BUILD_TARGET_ARCH
            value: "x86_64"
          - name: REPOSITORY_TRIGGER_URL
            value: "https://depot.haiku-os.org/__repository/haikuports/source/haikuports_x86_64/import"
      - name: buildmaster-x86-gcc2
        image: ghcr.io/haikuports/haikuporter/buildmaster:1.3.1-32-g6720
        #command: ["bootstrap", "x86_gcc2"]
        command: ["loop"]
        volumeMounts:
        - name: buildmaster-sources
          mountPath: /var/sources
        - name: buildmaster-data-x86-gcc2
          mountPath: /var/buildmaster
        - name: storage-secrets-master
          mountPath: "/run/secrets/storage_config"
        - name: signing-secrets
          mountPath: "/run/secrets/repo_signing"
          readOnly: true
        env:
          - name: STORAGE_BACKEND_CONFIG
            value: "/run/secrets/storage_config/storage-config-x86-gcc2.json"
          - name: SYSTEM_PACKAGE_BRANCH
            value: "r1beta5_111"
          - name: BUILD_TARGET_ARCH
            value: "x86_gcc2"
          - name: REPOSITORY_TRIGGER_URL
            value: "https://depot.haiku-os.org/__repository/haikuports/source/haikuports_x86_gcc2/import"
      - name: buildmaster-riscv64
        image: ghcr.io/haikuports/haikuporter/buildmaster:1.3.1-32-g6720
        #command: ["bootstrap", "riscv64"]
        command: ["loop"]
        volumeMounts:
        - name: buildmaster-sources
          mountPath: /var/sources
        - name: buildmaster-data-riscv64
          mountPath: /var/buildmaster
        - name: storage-secrets-master
          mountPath: "/run/secrets/storage_config"
        - name: signing-secrets
          mountPath: "/run/secrets/repo_signing"
          readOnly: true
        env:
          - name: STORAGE_BACKEND_CONFIG
            value: "/run/secrets/storage_config/storage-config-riscv64.json"
          - name: SYSTEM_PACKAGE_BRANCH
            value: "hrev58907"
          - name: BUILD_TARGET_ARCH
            value: "riscv64"
          - name: REPOSITORY_TRIGGER_URL
            value: "https://depot.haiku-os.org/__repository/haikuports/source/haikuports_riscv64/import"
      volumes:
        - name: buildmaster-sources
          persistentVolumeClaim:
            claimName: buildmaster-sources-pvc
        - name: buildmaster-data-x86-gcc2
          persistentVolumeClaim:
            claimName: buildmaster-data-x86-gcc2-pvc
        - name: buildmaster-data-x86-64
          persistentVolumeClaim:
            claimName: buildmaster-data-x86-64-pvc
        - name: buildmaster-data-riscv64
          persistentVolumeClaim:
            claimName: buildmaster-data-riscv64-pvc
        - name: buildmaster-old-packages
          persistentVolumeClaim:
            claimName: buildmaster-packages-pvc
        - name: storage-secrets-master
          projected:
            sources:
            - secret:
                name: buildmaster-storage-master
        - name: signing-secrets
          projected:
            sources:
            - secret:
                name: haiku-artifact-signing
                items:
                  - key: minisign-haiku-2019.key
                    path: privatekey
                  - key: minisign-haiku-2019.password
                    path: privatekeypass
---
# state data for builds like logs of buildruns, buildrun id
# tracking, builder connection information.
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: buildmaster-data-x86-64-pvc
spec:
  storageClassName: do-block-storage-retain
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
# state data for builds like logs of buildruns, buildrun id
# tracking, builder connection information.
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: buildmaster-data-x86-gcc2-pvc
spec:
  storageClassName: do-block-storage-retain
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
# state data for builds like logs of buildruns, buildrun id
# tracking, builder connection information.
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: buildmaster-data-riscv64-pvc
spec:
  storageClassName: do-block-storage
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
# all of the packages for Haikuports
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: buildmaster-package-buffer-pvc
spec:
  storageClassName: do-block-storage-retain
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: Service
metadata:
  name: buildmaster
spec:
  selector:
    app: buildmaster
  ports:
  - name: www
    port: 80
    targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: static-build
  labels:
    app: static-build
spec:
  replicas: 1
  selector:
    matchLabels:
      app: static-build
  template:
    metadata:
      labels:
        app: static-build
    spec:
      containers:
      - name: static-build
        image: ghcr.io/haiku/static-build:20250628
---
apiVersion: v1
kind: Service
metadata:
  name: static-build
spec:
  selector:
    app: static-build
  ports:
  - name: www
    port: 80
    targetPort: 80
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: strip-bm-prefix
spec:
  stripPrefix:
    prefixes:
      - /buildmaster/
      - /irccat/
---
# web frontend for buildmaster
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: buildmaster
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
    traefik.ingress.kubernetes.io/router.entrypoints: web,webs
    traefik.ingress.kubernetes.io/router.middlewares: default-errorku@kubernetescrd,default-strip-bm-prefix@kubernetescrd
spec:
  tls:
  - hosts:
    - build.haiku-os.org
    secretName: tls-cert-build
  rules:
  - host: build.haiku-os.org
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: static-build
            port:
              name: www
      - path: /buildmaster
        pathType: Prefix
        backend:
          service:
            name: buildmaster
            port:
              name: www
      - path: /irccat
        pathType: Prefix
        backend:
          service:
            name: irccat
            port:
              number: 80
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: buildmaster-pvbackup
spec:
  schedule: "0 6 * * 0"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          # volumes are attached to a single physical node (RWO), this ensures the backup
          # job always starts on the same physical node where buildmaster is running
          affinity:
            podAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
              - labelSelector:
                  matchExpressions:
                  - key: app
                    operator: In
                    values:
                    - buildmaster
                topologyKey: kubernetes.io/hostname
          containers:
            - name: pvbackup
              image: ghcr.io/haiku/pvbackup:3.0.2
              args: ["backup", "buildmaster-data"]
              env:
              - name: REMOTE_PREFIX
                value: haiku-backups
              - name: REMOTE_MAX_AGE
                value: 15d
              volumeMounts:
              - name: rclone-config
                mountPath: /root/.config
              - name: buildmaster-data-x86-64
                mountPath: /pvs/buildmaster-data/x86_64
              - name: buildmaster-data-x86-gcc2
                mountPath: /pvs/buildmaster-data/x86_gcc2
              - name: buildmaster-data-riscv64
                mountPath: /pvs/buildmaster-data/riscv64
          volumes:
          - name: buildmaster-data-x86-64
            persistentVolumeClaim:
              claimName: buildmaster-data-x86-64-pvc
          - name: buildmaster-data-x86-gcc2
            persistentVolumeClaim:
              claimName: buildmaster-data-x86-gcc2-pvc
          - name: buildmaster-data-riscv64
            persistentVolumeClaim:
              claimName: buildmaster-data-riscv64-pvc
          - name: rclone-config
            secret:
              secretName: s3-backup
              items:
              - key: rclone.conf
                path: rclone/rclone.conf
              - key: twosecret
                path: twosecret
          restartPolicy: Never
