#
# Haiku buildmaster
#
# Runs buildmasters which connect to various builders
# at various remote locations over ssh with verifie
# host keys.
#
apiVersion: apps/v1
kind: Deployment
metadata:
  name: haikuporter-new
  labels:
    app: haikuporter-new
spec:
  replicas: 1
  selector:
    matchLabels:
      app: buildmaster-new
  template:
    metadata:
      labels:
        app: buildmaster-new
    spec:
      containers:
      - name: buildmaster-frontend
        image: ghcr.io/haikuports/haikuporter/frontend:1.3.0-1
        volumeMounts:
        - name: buildmaster-data-riscv64
          mountPath: /var/instances/master/riscv64
        - name: buildmaster-packages-new
          mountPath: /var/instances/haikuports
      - name: buildmaster-riscv64
        image: ghcr.io/haikuports/haikuporter/buildmaster:1.3.0-1
        #command: ["bootstrap", "riscv64"]
        command: ["loop"]
        volumeMounts:
        - name: buildmaster-packages-new
          mountPath: /var/packages
        - name: buildmaster-data-riscv64
          mountPath: /var/buildmaster
        - name: storage-secrets-riscv64
          mountPath: "/run/secrets/storage_config"
        - name: signing-secrets
          mountPath: "/run/secrets/repo_signing"
          readOnly: true
        env:
          - name: STORAGE_BACKEND_CONFIG
            value: "/run/secrets/storage_config/storage-config.json"
          - name: SYSTEM_PACKAGE_BRANCH
            value: "r1beta5_72"
          - name: BUILD_TARGET_ARCH
            value: "riscv64"
          - name: REPOSITORY_TRIGGER_URL
            value: "https://depot.haiku-os.org/__repository/haikuports/source/haikuports_riscv64/import"
      volumes:
        - name: buildmaster-data-riscv64
          persistentVolumeClaim:
            claimName: buildmaster-data-riscv64-pvc
        - name: buildmaster-packages-new
          persistentVolumeClaim:
            claimName: buildmaster-packages-new-pvc
        - name: storage-secrets-riscv64
          projected:
            sources:
            - secret:
                name: buildmaster-storage-riscv64
        - name: signing-secrets
          projected:
            sources:
            - secret:
                name: haiku-artifact-signing
                items:
                  - key: minisign-haiku-2019.key
                    path: privatekey
                  - key: minisign-haiku-2019.password
                    path: privatekeypass
---
# state data for builds like logs of buildruns, buildrun id
# tracking, builder connection information.
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: buildmaster-data-riscv64-pvc
spec:
  #storageClassName: do-block-storage-retain
  storageClassName: do-block-storage
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
# all of the packages for Haikuports
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: buildmaster-packages-new-pvc
spec:
  #storageClassName: do-block-storage-retain
  storageClassName: do-block-storage
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: Service
metadata:
  name: buildmaster-new
spec:
  selector:
    app: buildmaster-new
  ports:
  - name: www
    port: 80
    targetPort: 80
#---
#apiVersion: apps/v1
#kind: Deployment
#metadata:
#  name: www-build-new
#  labels:
#    app: www-build-new
#spec:
#  replicas: 1
#  selector:
#    matchLabels:
#      app: www-build-new
#  template:
#    metadata:
#      labels:
#        app: www-build-new
#    spec:
#      containers:
#      - name: www-build-new
#        image: docker.io/haiku/www-build:latest
#---
#apiVersion: v1
#kind: Service
#metadata:
#  name: www-build-new
#spec:
#  selector:
#    app: www-build-new
#  ports:
#  - name: www
#    port: 80
#    targetPort: 80
#---
#apiVersion: traefik.io/v1alpha1
#kind: Middleware
#metadata:
#  name: strip-bm-prefix-new
#spec:
#  stripPrefix:
#    prefixes:
#      - /buildmaster/
#      - /irccat/
#---
# web frontend for buildmaster
#apiVersion: networking.k8s.io/v1
#kind: Ingress
#metadata:
#  name: buildmaster-new
#  annotations:
#    cert-manager.io/cluster-issuer: letsencrypt-production
#    traefik.ingress.kubernetes.io/router.entrypoints: web,webs
#    traefik.ingress.kubernetes.io/router.middlewares: default-strip-bm-prefix-new@kubernetescrd
#spec:
#  tls:
#  - hosts:
#    - buildnew.haiku-os.org
#    secretName: tls-cert-build
#  rules:
#  - host: buildnew.haiku-os.org
#    http:
#      paths:
#      - path: /
#        pathType: Prefix
#        backend:
#          service:
#            name: www-build-new
#            port:
#              name: www
#      - path: /buildmaster
#        pathType: Prefix
#        backend:
#          service:
#            name: buildmaster
#            port:
#              name: www
#      - path: /irccat
#        pathType: Prefix
#        backend:
#          service:
#            name: irccat
#            port:
#              number: 80
