### HaikuDepotServer
apiVersion: apps/v1
kind: Deployment
metadata:
  name: haikudepotserver
  labels:
    app: haikudepotserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: haikudepotserver
  strategy:
    # HDS needs a cross-instance cache before we can run multiple
    type: Recreate
  template:
    metadata:
      labels:
        app: haikudepotserver
    spec:
      containers:
      - name: haikudepotserver
        image: ghcr.io/haiku/haikudepotserver:1.0.170
        env:
        - name: SPRING_MAIL_HOST
          value: "smtp"
        - name: HDS_AUTHENTICATION_JWS_ISSUER
          value: "haikuinc.hds"
        - name: HDS_GRAPHICS_SERVER_BASE_URI
          value: "http://haikudepotserver-server-graphics:8085"
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:postgresql://postgres:5432/haikudepotserver"
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            secretKeyRef:
              name: haikudepotserver-pg
              key: username
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: haikudepotserver-pg
              key: password
        - name: HDS_ALERTS_REPOSITORY_ABSENT-UPDATES_TO
          valueFrom:
            secretKeyRef:
              name: haikudepotserver-notify
              key: emails
        resources:
          limits:
            cpu: "1.0"
            memory: "750Mi"
          requests:
            cpu: "0.50"
            memory: "750Mi"
        startupProbe:
          httpGet:
            path: /actuator/health
            port: 8081
          initialDelaySeconds: 30
          periodSeconds: 10
          failureThreshold: 60
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8081
          initialDelaySeconds: 10
          periodSeconds: 30
          failureThreshold: 2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: haikudepotserver-server-graphics
  labels:
    app: haikudepotserver-server-graphics
spec:
  replicas: 2
  selector:
    matchLabels:
      app: haikudepotserver-server-graphics
  template:
    metadata:
      labels:
        app: haikudepotserver-server-graphics
    spec:
      containers:
        - name: haikudepotserver-server-graphics
          image: ghcr.io/haiku/haikudepotserver-server-graphics:1.0.170
          env:
            - name: HDS_GFX_QUANTIZE
              value: "false"
          resources:
            limits:
              cpu: "1.0"
              memory: "320Mi"
            requests:
              cpu: "0.50"
              memory: "320Mi"
          startupProbe:
            httpGet:
              path: /actuator/health
              port: 8086
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 60
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8086
            initialDelaySeconds: 10
            periodSeconds: 30
            failureThreshold: 2
---
apiVersion: v1
kind: Service
metadata:
  name: haikudepotserver
spec:
  selector:
    app: haikudepotserver
  ports:
  - name: www
    port: 80
    targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: haikudepotserver-server-graphics
spec:
  selector:
    app: haikudepotserver-server-graphics
  ports:
    - name: www
      port: 80
      targetPort: 8085
---
# web frontends for haikudepotserver
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: haikudepotserver
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
    traefik.ingress.kubernetes.io/router.entrypoints: web,webs
spec:
  tls:
  - hosts:
    - depot.haiku-os.org
    secretName: tls-cert-haikudepotserver
  rules:
  - host: depot.haiku-os.org
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: haikudepotserver
            port:
              name: www
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: haikudepotserver-pgbackup
spec:
  schedule: "0 0 * * 1,4"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: pgbackup
              image: ghcr.io/haiku/pgbackup:1.1
              args: ["backup", "haikudepotserver"]
              env:
              - name: S3_HOST
                value: "https://s3.eu-west-1.wasabisys.com"
              - name: S3_BUCKET
                value: haiku-backups
              - name: S3_MAX_AGE
                value: 15d
              - name: S3_KEY
                valueFrom:
                  secretKeyRef:
                    name: s3-backup
                    key: s3_key
              - name: S3_SECRET
                valueFrom:
                  secretKeyRef:
                    name: s3-backup
                    key: s3_secret
              - name: TWOSECRET
                valueFrom:
                  secretKeyRef:
                    name: s3-backup
                    key: twosecret
              - name: PG_HOSTNAME
                value: postgres
              - name: PG_USERNAME
                valueFrom:
                  secretKeyRef:
                    name: postgres-admin
                    key: username
              - name: PG_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: postgres-admin
                    key: password
