apiVersion: apps/v1
kind: Deployment
metadata:
  name: irccat
  labels:
    app: irccat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: irccat
  template:
    metadata:
      labels:
        app: irccat
    spec:
      containers:
      - name: irccat
        image: ghcr.io/irccloud/irccat:0.4.9
        resources:
          limits:
            cpu: "0.25"
            memory: "256Mi"
          requests:
            cpu: "0.15"
            memory: "128Mi"
        volumeMounts:
        - name: config
          mountPath: /run/secrets
      volumes:
      - name: config
        secret:
          secretName: irccat-config
          items:
          - key: config
            path: irccat.json
---
apiVersion: v1
kind: Service
metadata:
  name: irccat
spec:
  selector:
    app: irccat
  ports:
  - name: web
    port: 80
    targetPort: 8045
