### Haiku Pootle
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pootle
  labels:
    app: pootle
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pootle
  strategy:
    # RollingUpgrade can't be used because of RWO storage
    type: Recreate
  template:
    metadata:
      labels:
        app: pootle
    spec:
      containers:
      - name: pootle
        image: ghcr.io/haiku/pootle:2.7.6-1
        resources:
          limits:
            cpu: "2.0"
            memory: "1Gi"
          requests:
            cpu: "0.25"
            memory: "48Mi"
        volumeMounts:
        - name: pootle-data
          mountPath: /var/pootle
      volumes:
      - name: pootle-data
        persistentVolumeClaim:
          claimName: pootle-data-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pootle-data-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: Service
metadata:
  name: pootle
spec:
  selector:
    app: pootle
  ports:
  - name: web
    port: 80
    targetPort: 80
---
# web frontends for pootle
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pootle
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
    traefik.ingress.kubernetes.io/router.entrypoints: web,webs
spec:
  tls:
  - hosts:
    - i18n.haiku-os.org
    secretName: tls-cert-i18n
  rules:
  - host: i18n.haiku-os.org
    http:
      paths:
      - path: /pootle
        pathType: Prefix
        backend:
          service:
            name: pootle
            port:
              name: web
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: pootle-pgbackup
spec:
  schedule: "0 0 * * 1,4"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: pgbackup
              image: ghcr.io/haiku/pgbackup:1.1
              args: ["backup", "pootle_production"]
              env:
              - name: S3_HOST
                value: "https://s3.eu-west-1.wasabisys.com"
              - name: S3_REGION
                value: eu-west-1
              - name: S3_PROVIDER
                value: Wasabi
              - name: S3_BUCKET
                value: haiku-backups
              - name: S3_MAX_AGE
                value: 15d
              - name: S3_KEY
                valueFrom:
                  secretKeyRef:
                    name: s3-backup
                    key: s3_key
              - name: S3_SECRET
                valueFrom:
                  secretKeyRef:
                    name: s3-backup
                    key: s3_secret
              - name: TWOSECRET
                valueFrom:
                  secretKeyRef:
                    name: s3-backup
                    key: twosecret
              - name: PG_HOSTNAME
                value: postgres
              - name: PG_USERNAME
                valueFrom:
                  secretKeyRef:
                    name: postgres-admin
                    key: username
              - name: PG_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: postgres-admin
                    key: password
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: pootle-pvbackup
spec:
  schedule: "0 1 * * 1,4"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          # volumes are attached to a single physical node (RWO), this ensures the backup
          # job always starts on the same physical node where pootle is running
          affinity:
            podAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
              - labelSelector:
                  matchExpressions:
                  - key: app
                    operator: In
                    values:
                    - pootle
                topologyKey: kubernetes.io/hostname
          containers:
            - name: pvbackup
              image: ghcr.io/haiku/pvbackup:3.0.2
              args: ["backup", "pootle-data"]
              env:
              - name: REMOTE_PREFIX
                value: haiku-backups
              - name: REMOTE_MAX_AGE
                value: 15d
              volumeMounts:
              - name: rclone-config
                mountPath: /root/.config
              - name: pootle-data
                mountPath: /pvs/pootle-data
          volumes:
          - name: pootle-data
            persistentVolumeClaim:
              claimName: pootle-data-pvc
          - name: rclone-config
            secret:
              secretName: s3-backup
              items:
              - key: rclone.conf
                path: rclone/rclone.conf
              - key: twosecret
                path: twosecret
          restartPolicy: Never
