### Haiku Postgres
#
# Private postgres database
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  labels:
    app: postgres
    version: "14"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
      version: "14"
  template:
    metadata:
      labels:
        app: postgres
        version: "14"
    spec:
      containers:
      - name: postgres
        image: docker.io/postgres:14.18-alpine
        env:
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdb
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgres-admin
              key: username
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-admin
              key: password
        resources:
          limits:
            cpu: "2.0"
            memory: "4Gi"
          requests:
            cpu: "0.25"
            memory: "512Mi"
        volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: postgres-data
        persistentVolumeClaim:
          claimName: postgres-data-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-data-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 80Gi
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  selector:
    app: postgres
    version: "14"
  ports:
  - name: postgres
    port: 5432
    targetPort: 5432
