apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: haiku-release-mirror
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: haiku-release-mirror
spec:
  schedule: "0 6 * * 0"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      suspend: true
      template:
        spec:
          # volumes are attached to a single physical node (RWO), this ensures the backup
          # job always starts on the same physical node where gerrit is running
          affinity:
            podAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
              - labelSelector:
                  matchExpressions:
                  - key: app
                    operator: In
                    values:
                    - buildmaster
                topologyKey: kubernetes.io/hostname
          restartPolicy: Never
          containers:
            - name: rclone-mirror
              image: ghcr.io/haiku/rclone-mirror:3.15-3
              env:
              - name: BACKEND
                value: s3
              - name: BUCKET
                value: haiku-release
              - name: S3_ENDPOINT
                value: "https://s3.us-east-1.wasabisys.com"
              - name: S3_ACCESS_KEY
                valueFrom:
                  secretKeyRef:
                    name: wasabi-access-ro-s3
                    key: s3_key
              - name: S3_SECRET_KEY
                valueFrom:
                  secretKeyRef:
                    name: wasabi-access-ro-s3
                    key: s3_secret
              volumeMounts:
              - name: haiku-release-mirror
                mountPath: /data
          volumes:
          - name: haiku-release-mirror
            persistentVolumeClaim:
              claimName: haiku-release-mirror
