### Haiku Pootle
apiVersion: apps/v1
kind: Deployment
metadata:
  name: static-i18n
  labels:
    app: static-i18n
spec:
  replicas: 2
  selector:
    matchLabels:
      app: static-i18n
  template:
    metadata:
      labels:
        app: static-i18n
    spec:
      containers:
      - name: static-i18n
        image: ghcr.io/haiku/static-i18n:20250110
        resources:
          limits:
            cpu: "0.50"
            memory: "256Mi"
          requests:
            cpu: "0.15"
            memory: "128Mi"
        startupProbe:
          httpGet:
            path: /
            port: 80
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 1
        livenessProbe:
          httpGet:
            port: 80
            path: /
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: static-i18n-pdb
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: static-i18n
---
apiVersion: v1
kind: Service
metadata:
  name: static-i18n
spec:
  selector:
    app: static-i18n
  ports:
  - name: web
    port: 80
    targetPort: 80
---
# web frontends for trac
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: static-i18n-web
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
    traefik.ingress.kubernetes.io/router.entrypoints: web,webs
spec:
  tls:
  - hosts:
    - i18n.haiku-os.org
    secretName: tls-cert-i18n
  rules:
  - host: i18n.haiku-os.org
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: static-i18n
            port:
              name: web
