#
# THIS IS AN EXAMPLE AND NEEDS CUSTOMIZED TO FUNCTION
#
apiVersion: batch/v1
kind: Job
metadata:
  name: restore
spec:
  template:
    spec:
      # volumes are attached to a single physical node (RWO), this ensures the restore
      # job always starts on the same physical node where the application is running
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - git
            topologyKey: kubernetes.io/hostname
      restartPolicy: Never
      containers:
      - name: pvbackup
        image: ghcr.io/haiku/pvbackup:1.3
        args: ["restore", "gerrit-data"]
        env:
        - name: S3_HOST
          value: "https://s3.eu-west-1.wasabisys.com"
        - name: S3_BUCKET
          value: haiku-backups
        - name: S3_MAX_AGE
          value: 60d
        - name: S3_KEY
          valueFrom:
            secretKeyRef:
              name: s3-backup
              key: s3_key
        - name: S3_SECRET
          valueFrom:
            secretKeyRef:
              name: s3-backup
              key: s3_secret
        - name: TWOSECRET
          valueFrom:
            secretKeyRef:
              name: s3-backup
              key: twosecret
        volumeMounts:
        - name: gerrit-data
          mountPath: /pvs/gerrit-data
      volumes:
      - name: gerrit-data
        persistentVolumeClaim:
          claimName: gerrit-data-pvc
      restartPolicy: Never
