#
# THIS IS AN EXAMPLE AND NEEDS CUSTOMIZED TO FUNCTION
#
apiVersion: batch/v1
kind: Job
metadata:
  name: restore
spec:
  template:
    spec:
      # volumes are attached to a single physical node (RWO), this ensures the restore
      # job always starts on the same physical node where the application is running
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - git
            topologyKey: kubernetes.io/hostname
      restartPolicy: Never
      containers:
      - name: pvbackup
        image: ghcr.io/haiku/pvbackup:3.0.2
        args: ["restore", "gerrit-data"]
        env:
        - name: REMOTE_PREFIX
          value: haiku-backups
        - name: REMOTE_MAX_AGE
          value: 15d
        volumeMounts:
        - name: rclone-config
          mountPath: /root/.config
        - name: gerrit-data
          mountPath: /pvs/gerrit-data
      volumes:
        - name: gerrit-data
          persistentVolumeClaim:
            claimName: gerrit-data-pvc
        - name: rclone-config
          secret:
            secretName: s3-backup
            items:
            - key: rclone.conf
              path: rclone/rclone.conf
            - key: twosecret
              path: twosecret
          restartPolicy: Never
