# INSTRUCTIONS
# USED TO RESTORE DATA FROM OUR S3 BUCKETS
# PRE-REQUIREMENTS:
#   * s3-backup secret in place
#   * postgres-admin secret in place
#   * postgresql running in cluster
#
# USAGE:
#   One job should be started per database
#   Be sure to customize args for each database to be restored
#   kubectl apply -f restore-pg.yml
#   kubectl logs jobs/restore
#
apiVersion: batch/v1
kind: Job
metadata:
  name: restore
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: pgbackup
        image: ghcr.io/haiku/pgbackup:3.0.4
        args: ["restore", "trac"]
        env:
        - name: REMOTE_PREFIX
          value: haiku-backups
        - name: PG_HOSTNAME
          value: postgres
        - name: PG_USERNAME
          valueFrom:
            secretKeyRef:
              name: postgres-admin
              key: username
        - name: PG_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-admin
              key: password
        volumeMounts:
        - name: rclone-config
          mountPath: /root/.config
      volumes:
      - name: rclone-config
        secret:
          secretName: s3-backup
          items:
          - key: rclone.conf
            path: rclone/rclone.conf
          - key: twosecret
            path: twosecret
