name: Build general-worker
on:
  push:
    tags:
      - general-worker-*
  pull_request:
    branches:
      - main
jobs:
  build:
    name: Build general-worker
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Detect version
      id: detect-version
      run: echo "RELEASE_VERSION=$(git describe --dirty --tags --match=general-worker-* --abbrev=1 | sed -r 's/general-worker-//')" >> "$GITHUB_OUTPUT"
    - name: List version
      run: echo "Building ${{ steps.detect-version.outputs.RELEASE_VERSION }}..."
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to Github Container registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and push multi-architecture image
      uses: docker/build-push-action@v5
      with:
        context: containers/general-worker
        push: true
        tags: |
          ghcr.io/haiku/general-worker:${{ steps.detect-version.outputs.RELEASE_VERSION }}-amd64
          ghcr.io/haiku/general-worker:${{ steps.detect-version.outputs.RELEASE_VERSION }}-arm64
        platforms: linux/amd64,linux/arm64
    - uses: int128/docker-manifest-create-action@v2
      with:
        tags: ghcr.io/haiku/general-worker:${{ steps.detect-version.outputs.RELEASE_VERSION }}
      sources: |
        ghcr.io/haiku/general-worker:${{ steps.detect-version.outputs.RELEASE_VERSION }}-amd64
        ghcr.io/haiku/general-worker:${{ steps.detect-version.outputs.RELEASE_VERSION }}-arm64


